apiVersion: apps/v1
kind: Deployment
metadata:
  name: huco
  labels:
    app: huco
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: huco
  template:
    metadata:
      labels:
        app: huco
        tier: huco
    spec:
      containers:
      - name: huco
        image: project0620/huco:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: huco
        env:
        - name: "GOOGLE_APPLICATION_CREDENTIALS"
          value: "/var/run/secret/cloud.google.com/service-account.json"
        envFrom:
        - secretRef:
            name: backend-secret
        volumeMounts:
        - name: "service-account"
          mountPath: "/var/run/secret/cloud.google.com"
      volumes:
        - name: "service-account"
          secret:
            secretName: "huco-sa-key"
---
apiVersion: v1
kind: Service
metadata:
  name: huco
  labels:
    app: huco
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: huco
    tier: huco
  type: LoadBalancer
